sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - cd backend
  - chmod +x mvnw
  
addons:
  sonarcloud:
  organization: "losaodluka01"
  token: "c2c4402266138d4de2a875569d9e25a7156dcd7a"

script:
  - ./mvnw clean install -DskipTests=true -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=losaodluka01_ISA_MRS -Dsonar.organization=losaodluka01 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c2c4402266138d4de2a875569d9e25a7156dcd7a

dist: trusty

deploy:
  provider: heroku
  api_key: 1366be50-2ae0-472c-95fd-b3e0cd7038ef
  app: eclinic05

